apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-service
  template:
    metadata:
      labels:
        app: monitor-service
    spec:
      containers:
      - name: monitor-service
        image: monitor-service:latest
---
apiVersion: v1
kind: Service
metadata:
  name: monitor-service
spec:
  selector:
    app: monitor-service
  ports:
    - port: 3004
      targetPort: 3004